version: '3'

services:
  correct-pypy:
    build:
      context: .
      args:
        - IMAGE_NAME=${PYPY_IMAGE_NAME}
        - IMAGE_VERSION=${PYPY_IMAGE_VERSION}
    image: lycantropos/correct-pypy:0.0.0-alpha
    volumes:
      - ./correct:/opt/correct/correct
      - ./pytest.ini:/opt/correct/pytest.ini
      - ./README.md:/opt/correct/README.md
      - ./requirements-tests.txt:/opt/correct/requirements-tests.txt
      - ./requirements.txt:/opt/correct/requirements.txt
      - ./setup.py:/opt/correct/setup.py
      - ./tests:/opt/correct/tests
    entrypoint: pytest
